# syntax = docker/dockerfile:1.0-experimental
FROM quay.io/openshiftlabs/cloudnative-workspaces-quarkus:1.3

USER root

# Need to run this first to avoid an error later on when running subscription manager
RUN yum update -y --skip-broken --allowerasing --nobest

RUN subscription-manager register --username="foo" --password="bar" --auto-attach

RUN yum install -y zsh

# finally, reclaim rhel license as we're done installing things with yum
RUN subscription-manager unregister

# return to original user
USER jboss

# install oh-my-zsh framework
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"