FROM quay.io/openshiftlabs/cloudnative-workspaces-quarkus:1.3

USER root

ARG HOST_SECRETS_DIR

# Need to run this first to avoid an error later on when running subscription manager
RUN yum update -y --skip-broken --allowerasing --nobest

COPY ${HOST_SECRETS_DIR}/myuser_secret.txt /run/secrets/myuser.txt
COPY ${HOST_SECRETS_DIR}/mypass_secret.txt /run/secrets/mypass.txt

RUN echo subscription-manager register --username="$(cat /run/secrets/myuser.txt)" --password="$(cat /run/secrets/mypass.txt)" --auto-attach && \
    rm -r /run/secrets/my*.txt

RUN yum install -y zsh

# finally, reclaim rhel license as we're done installing things with yum
RUN subscription-manager unregister

# return to original user
USER jboss

# install oh-my-zsh framework
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"