FROM quay.io/openshiftlabs/cloudnative-workspaces-quarkus:1.3

ARG RHEL_user
ARG RHEL_pass

USER root

# Need to run this first to avoid an error later on when running subscription manager
RUN yum update -y --skip-broken --allowerasing --nobest

# Register with the subscription manager so that we can install new packages
RUN subscription-manager register --username="$RHEL_user" --password="$RHEL_pass" --auto-attach

RUN yum install -y zsh

# finally, reclaim rhel license as we're done installing things with yum
RUN subscription-manager unregister

# return to original user
USER jboss

# install oh-my-zsh framework
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"